### ISSUE TITLE
Data splits

### ISSUE THREAD

**Issue by spookyQubit** [jitkapat/TopicReg#2]
Hi @jitkapat , thanks a lot for releasing the code. 
In order to reproduce the scores, we are wondering if it is possible to get the exact `train/dev/test` splits corresponding to `Cross-topic test` and `In-distribution-topic` settings? 
Having the exact splits (or the script to create the splits) will greatly benefit reproducibility. -- Thanks.

**Comment by jitkapat** [comment]
Hi @spookyQubit. Thanks for your interest in our project! I do have the data splits available, but could not release it publicly due to license issues. If there is any further request, please send me an email.

**Comment by spookyQubit** [comment]
Hi @jitkapat , thanks so much for getting back. Really appreciate it. 

I looked into the data repositories. I seems that:
1. For [Reddit](https://zenodo.org/records/3608135), the data actually has an open access policy (attaching screenshot below).  
<img width="874" alt="Screenshot 2024-01-20 at 12 14 16 PM" src="https://github.com/jitkapat/TopicReg/assets/14355634/89819325-5f2f-42ea-bc9d-7983b31f1316">
It should be ok to share this data. 

2. For [Fanfiction](https://zenodo.org/records/5106099) also, the data seems to have an open access policy. It should be ok to share this data too.

3. The [Amazon](https://nijianmo.github.io/amazon/index.html) data does not seem to have an open access policy. So, I agree that sharing this data would be difficult. 

Would be really helpful to get the splits at least for Reddit/PAN. -- Thanks.

**Comment by jitkapat** [comment]
Hi! I am willing to share; just not that we can publish it on our repository. Could you please email me (jitkapat.s_s20@vistec.ac.th)?

**Comment by spookyQubit** [comment]
Thanks a lot @jitkapat , i received the data. Really appreciate your help.
